import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./_components/layout/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "file.rocks - Open-Source S3 File Management",
  description: "Generated by create next app",
};

export default function Example() {
  return (
    <html className="h-full bg-white">
      <body className="h-full">
        <div>
          <Sidebar />
          <main className="py-10 lg:pl-72">
            <div className="px-4 sm:px-6 lg:px-8">{/* Your content */}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
